bbackend:
  name: github
  repo: matthieu2910/chalet-lievre-verbier-2
  branch: main
  auth_type: implicit
  app_id: ${GITHUB_CLIENT_ID}

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Page d'accueil"
    files:
      - file: "home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Texte", name: "body", widget: "markdown" }
          - { label: "Galerie", name: "gallery", widget: "list", field: {label: "Image", name: "image", widget: "image"} }

  - name: "chalet"
    label: "Chalet"
    files:
      - file: "chalet.md"
        label: "Chalet Lièvre"
        name: "chalet"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Caractéristiques", name: "features", widget: "markdown" }
          - { label: "Photos", name: "photos", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
